a=input("enter the name,address,phone number,mail id\ncollege,school and percentage:\n")
a=a.split()
#print(a)
"""b=input('Enter the address')
c=input('Enter the phone number')
d=input('enter the mail id')
e=input("enter the college and percentage")
e=e.split()
f=input("enter the school and the percentage")
f=f.split()"""
print("PERSONAL DETAIL:\n--------------------------------------------")
print("Name:        ",a[0])
print("Address:     ",a[1])
print("Phone number:",a[2])
print("Mail-id:     ",a[3])
print("EDUCATION:\n----------------------------------------------")
print("UG:  ",a[4],",",a[5])
print("10th:",a[8],",",a[9])
print("12th:",a[6],",",a[7])
